version: '3.8'

services:
  app:
    build: .
    ports:
      - "8045:8045"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mongo_data:
    external: false
